export const SET_PAGE = "SET_PAGE";
export const SET_ROWS_PER_PAGE = "SET_ROWS_PER_PAGE";
export const SET_SELECTED_ROWS = "SET_SELECTED_ROWS";
export const EMAIL_DETAILS = "EMAIL_DETAILS";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
export const LOGOUT = "LOGOUT";
